import Registration from '@/components/register/Registration';

export const metadata = {
  title: "MovieDB -> Registration",
  description: "Generated by github/muhamash a NextJs app",
};

export default function registrationPage() {
  return (
    <div className='w-full h-screen flex items-center justify-center'>
      <Registration/>
    </div>
  )
}
