import Nav from "@/components/Nav";
import { dancingScript, lato, manrope, nunito } from "./fonts/font";
import "./globals.css";

export const metadata = {
  title: "MovieDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.className} ${nunito.className} ${dancingScript.className} ${lato.className}`}
    >
      <body className="antialiased bg-black text-white">
        <Nav/>
        { children }
      </body>
    </html>
  );
}