import { cinzel, dancingScript, nunito } from "./fonts/font";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cinzel.className} ${nunito.className} ${dancingScript.className}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}