import Login from '@/components/login/Login';
 
export const metadata = {
  title: "MovieDB -> Login",
  description: "Generated by github/muhamash a NextJs app",
};

export default function loginPage() {
  return (
    <div className='w-full h-screen flex justify-center items-center'>
      <Login/>
    </div>
  )
}
