import WatchList from '@/components/watchList/WatchList';

export const metadata = {
  title: "MovieDB -> Watch list",
  description: "Generated by github/muhamash a NextJs app",
};

export default async function WatchListPage ({ params} )
{
  return (
    <>
      <WatchList id={params?.userId}/>
    </>
  );
}
